# Generated by Django 5.1.2 on 2024-10-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_alter_locationoperatinghours_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationoperatinghours",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
